[workspace]
members = ["src/oracle_canister", "src/register_evm_agent"]

[workspace.package]
version = "0.1.0"
edition = "2021"


[workspace.dependencies]
anyhow = "1.0"
candid = "0.8"
clap = { version = "4.2.4", features = ["derive"] }
dirs = "5.0"
env_logger = "^0.10"
eth-signer = { git = "https://github.com/infinity-swap/eth-signer", tag = "v0.2.0" }
# infinityswap.atlassian.net/browse/EPROD-153 - We are currently depending on a commit, will be removed when new version is released
ethers-core = { git = "https://github.com/infinity-swap/ethers-rs", default-features = false, package = "ethers-core", branch = "evmc_fork" }
evmc-did = { git = "https://github.com/infinity-swap/evmc-did", tag = "v0.2.0" }
hex = "0.4"
ic-agent = "0.24.0"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", tag = "v0.3.45" }
ic-exports = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-exports", tag = "v0.3.45" }
ic-stable-structures = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-stable-structures", tag = "v0.3.45" }
log = "^0.4"
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
rlp = "0.5"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.24", features = ["macros", "rt"] }
url = { version = "2.3.1", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
