[package]
name = "register_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.8"
ethers-core = { git = "https://github.com/infinity-swap/ethers-rs", default-features = false, package = "ethers-core", branch = "evmc_fork" }
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
ic-agent = "0.23.0"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
rlp = "0.5"
tokio = { version = "1.24", features = ["macros", "rt"] }
hex = "0.4"
ic-exports = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-exports", tag = "v0.3.42" }
eth-signer = { git = "ssh://git@github.com/infinity-swap/evm-canister", package = "eth-signer" }
did = { git = "ssh://git@github.com/infinity-swap/evm-canister", package = "did" }
evm_adapter = { git = "ssh://git@github.com/infinity-swap/evm-canister", package = "evm_adapter" }
clap = { version = "4.2.4", features = ["derive"] }
dirs = "4.0.0"
