[workspace]
members = [
    "src/did",
    "src/eth-signer",
    "src/register-evm-agent/src/simple_canister",
    "src/register-evm-agent/src/register_evm_agent",
]

[workspace.package]
authors = ["Bitfinity Network"]
categories = ["cryptography::cryptocurrencies"]
description = "EVM canister SDK"
edition = "2021"
homepage = "https://github.com/infinity-swap/evmc-sdk"
include = ["src/**/*", "LICENSE", "README.md"]
license = "MIT"
name = "evmc-sdk"
repository = "https://github.com/infinity-swap/evmc-sdk"
version = "0.2.4"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "1.3"
candid = "0.8"
# Using fixed chrono version. See: https://infinityswap.atlassian.net/browse/EPROD-45
chrono = "=0.4.19"
clap = { version = "4", features = ["derive"] }
derive_more = "0.99"
env_logger = { version = "0.10.0", default-features = false }
ethereum-types = "0.14"
ethers = "2.0.6"
# infinityswap.atlassian.net/browse/EPROD-153 - We are currently depending on a commit, will be removed when new version is released
ethers-core = { git = "https://github.com/infinity-swap/ethers-rs", default-features = false, package = "ethers-core", branch = "evmc_fork" }
hash-db = "0.15"
hex = "0.4"
ic-agent = "0.24"
ic-canister = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-canister", tag = "v0.3.x" }
ic-exports = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-exports", tag = "v0.3.x" }
ic-stable-structures = { git = "https://github.com/infinity-swap/canister-sdk", package = "ic-stable-structures", tag = "v0.3.x" }
is20-token = { git = "https://github.com/infinity-swap/IS20", tag = "v1.x" }
jsonrpc-core = "18.0"
log = "0.4"
mockall = "0.11"
num = "0.4"
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
reqwest = { version = "0.11", default-features = false }
serde = "1.0"
serde_json = "1.0"
rlp = "0.5"
sha2 = "0.10"
sha3 = "0.10"
thiserror = "1.0"
tokio = { version = "1.24", features = ["macros", "rt"] }
