version: "3.3"

#
# This docker-compose file is used to start the services for local testing.
# It starts a evm-blockchain-extractor connected to a local postgres database.
#

services:

  db:
    image: "postgres:11-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres


  extractor:
    image: ghcr.io/bitfinity-network/evm-block-extractor:main
    # image: "evm-block-extractor:latest"
    # build: 
    #   dockerfile: ./src/evm-block-extractor/Dockerfile
    ports:
      - "8080:8080"
    command: --rpc-url https://testnet.bitfinity.network --postgres --username postgres --password postgres --database-name postgres --database-url db
