[package]
name = "evm-block-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "evm-block-extractor"
path = "src/bin/extractor.rs"

[[bin]]
name = "evm-block-extractor-server"
path = "src/bin/server.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
ethers-core = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
ethereum-json-rpc-client = { path = "../ethereum-json-rpc-client", features = [
  "reqwest",
] }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["postgres"] }
tokio = { workspace = true }
zip = { workspace = true }
gcp-bigquery-client = { workspace = true }
async-trait = { workspace = true }
jsonrpsee = { workspace = true }
yup-oauth2 = { workspace = true }
did = { path = "../did" }
futures = { workspace = true }
[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }
testcontainers = { workspace = true }
wiremock = { workspace = true }
