name: Block Extractor Workflow

on:
  schedule:
    - cron: '0 */3 * * *'

env:
  RUST_LOG: info
  GCP_BLOCK_EXTRACTOR_SA_KEY: ${{ secrets.GCP_BLOCK_EXTRACTOR_SA_KEY }}

jobs:
  backup-blocks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [postgres, bigquery]
        network: [mainnet, testnet]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile evm-block-extractor
        run: cargo build --release -p evm-block-extractor --bin evm-block-extractor-server

      - name: Move binary to root
        run: mv target/release/evm-block-extractor-server evm-block-extractor-server

      - name: Make binary executable
        run: chmod +x evm-block-extractor-server

      - name: Run evm-block-extractor for BigQuery
        if: matrix.database == 'bigquery'
        run: |
          ./evm-block-extractor \
              --rpc-url ${{ env.rpc_url }} \
              --max-number-of-requests 100 \
              --database bigquery \
              --network ${{ matrix.network }} \
              --project-id ${{ secrets.BIGQUERY_PROJECT_ID }} \
              --dataset-id ${{ secrets.BIGQUERY_DATASET_ID }} \
              --sa-key ${{ env.GCP_BLOCK_EXTRACTOR_SA_KEY }}

      - name: Run evm-block-extractor for Postgres
        if: matrix.database == 'postgres'
        run: |
          ./evm-block-extractor \
              --rpc-url ${{ env.rpc_url }} \
              --max-number-of-requests 100 \
              --database postgres \
              --network ${{ matrix.network }} \
              --username ${{ secrets.POSTGRES_USERNAME }} \
              --password ${{ secrets.POSTGRES_PASSWORD }}
              --database-name ${{ secrets.POSTGRES_DATABASE_NAME  }} \
              --database-url ${{ secrets.POSTGRES_DATABASE_URL }} \
              --database-port ${{ secrets.POSTGRES_DATABASE_PORT }}
