name: 'Deploy EVM Block Extractor to GCP Registry'

on:
  workflow_dispatch: {}

  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publishing-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCP Registry
        uses: docker/login-action@v2
        with:
          registry: us-east4-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Building CloudRun image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./src/evm-block-extractor/Dockerfile
          tags: |
            us-central1-docker.pkg.dev/dfx-server/evm-block-extractor/evm-block-extractor-server:latest
